name: Lint Python
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    runs-on: ubuntu-latest
    name: Lint workflow with pytest
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2
    - name: Linting + Pytest
      uses: alexanderdamiani/pylinter@v1.2.0
