name: Lint Python
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2
    - name: linting
      uses: alexanderdamiani/pylinter@v1.2.0
